# ALL UNITS IN SI

# field dimensions
field:
  width: 3
  length: 4.25
  wall_thickness: 0.25
  goal:
    width: 1

# car dimensions and physical constants
ball:
  radius: 0.0508 # (2 in)

# car dimensions and physical constants
cars:
  length: 0.12  # front to rear wheel center to center, meters
  steering:
    max_throw: 0.1826  # center to side, radians
    rate: 0.9128  # rad/s
  throttle:
    max_speed: 2.3  # m/s
    tau: 0.2  # time constant, seconds
