image_width: 1288
image_height: 964
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [ 622.97553,    0.     ,  629.52047,
            0.     ,  623.06713,  531.64699,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.245361, 0.051611, 0.001780, -0.001882, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 458.35803,    0.     ,  623.37666,    0.     ,
            0.     ,  506.30353,  559.48128,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
