image_width: 1288
image_height: 964
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [ 663.01542,    0.     ,  671.56566,
            0.     ,  665.19874,  484.66114,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.231935, 0.037963, -0.003778, 0.000238, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 460.73627,    0.     ,  697.05059,    0.     ,
            0.     ,  566.45935,  478.06261,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
