standalone_tags:
  [
    { id: 10, size: 0.07 },
    { id: 11, size: 0.07 },
    { id: 12, size: 0.07 },
    { id: 13, size: 0.07 },
  ]
tag_bundles:
  [
    {
      name: 'field_origin',
      layout:
        [
          {id: 0, size: 0.2, x: -1.8081, y:  1.1742, z: -0.0308, qw:  0.9997, qx:  0.0099, qy:  0.0046, qz:  0.0197},
          {id: 1, size: 0.2, x:  0.0701, y:  1.3045, z: -0.0291, qw:  0.9998, qx: -0.0116, qy: -0.0007, qz:  0.0161},
          {id: 2, size: 0.2, x:  1.7377, y:  1.2590, z: -0.0244, qw:  0.9998, qx:  0.0085, qy: -0.0038, qz:  0.0152},
          {id: 3, size: 0.2, x: -1.1869, y:  0.0000, z:  0.0000, qw:  1.0000, qx:  0.0000, qy:  0.0000, qz:  0.0000},
          {id: 4, size: 0.2, x:  1.1869, y:  0.0138, z: -0.0036, qw:  0.9998, qx:  0.0047, qy: -0.0161, qz:  0.0089},
          {id: 5, size: 0.2, x: -1.7244, y: -1.2670, z:  0.0111, qw:  0.9998, qx:  0.0008, qy: -0.0024, qz:  0.0208},
          {id: 6, size: 0.2, x:  0.1233, y: -1.2090, z:  0.0012, qw:  0.9998, qx:  0.0023, qy:  0.0177, qz:  0.0000},
          {id: 7, size: 0.2, x:  1.8482, y: -1.0850, z:  0.0030, qw:  0.9999, qx: -0.0131, qy: -0.0009, qz: -0.0015}
        ]
    }
  ]