throttle:
  gains:  
    kp: 0.05
    ki: 0.0
    kd: 0.0
    kff: 0.0
  deadband: 0.01
  anti_windup: 0.0
  static_friction: 0.01
  limits:
    min: -1.0
    max: 1.0

steering:
  gains:  
    kp: 1.0
    ki: 0.0
    kd: 0.0
    kff: 0.0
  deadband: 0.01
  anti_windup: 0.0
  static_friction: 0.01
  limits:
    min: -1.0
    max: 1.0