name: Top-level push workflow

on:
  push:
    branches: ['main']

jobs:
  changes:
    name: Check for changes to files in docker directory
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.changes.outputs.docker }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            docker: ['docker/**']
  docker:
    name: Rebuild Docker image and push to latest
    needs: changes
    if: needs.changes.outputs.docker == 'true'
    uses: purdue-arc/rocket_league/.github/workflows/docker-build-push.yml@main
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  catkin:
    name: Catkin build and test using latest Docker image
    needs: docker
    uses: purdue-arc/rocket_league/.github/workflows/catkin-build-test.yml@main
